"""Add first_name and last_name to User

Revision ID: 572443072ebf
Revises: 573e8e5a72c9
Create Date: 2024-01-30 05:35:53.682475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572443072ebf'
down_revision = '573e8e5a72c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
