"""Add functionality adding recipe to calendar

Revision ID: 614ea952ecec
Revises: 2a5327233b46
Create Date: 2024-01-30 08:36:10.228124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614ea952ecec'
down_revision = '2a5327233b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.alter_column('recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_calendar_recipes_calendar_id_calendars', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_calendar_recipes_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('calendar_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_calendar_recipes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_calendar_recipes_calendar_id_calendars', 'calendars', ['calendar_id'], ['id'])
        batch_op.alter_column('recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
