"""Add instructions column to recipes

Revision ID: 744a9570f0dc
Revises: 1383a0905f68
Create Date: 2024-02-02 01:59:07.626863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744a9570f0dc'
down_revision = '1383a0905f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('directions')

    # ### end Alembic commands ###
