"""added image column to recipes db

Revision ID: 8500af617347
Revises: 744a9570f0dc
Create Date: 2024-02-03 14:20:03.692599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8500af617347'
down_revision = '744a9570f0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ingredients_name'), ['name'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ingredients_name'), type_='unique')

    # ### end Alembic commands ###
