"""updating relationships

Revision ID: d8ff388032dd
Revises: 614ea952ecec
Create Date: 2024-01-31 02:33:43.336428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ff388032dd'
down_revision = '614ea952ecec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_calendar_recipes_calendar_id_calendars'), 'calendars', ['calendar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_calendar_recipes_calendar_id_calendars'), type_='foreignkey')
        batch_op.drop_column('calendar_id')

    # ### end Alembic commands ###
