"""Add author to Recipe

Revision ID: ff2778ed36dd
Revises: 572443072ebf
Create Date: 2024-01-30 06:26:56.319692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2778ed36dd'
down_revision = '572443072ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipes_author_id_users'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_author_id_users'), type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
